// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBuBetfcqPdxJeOV9J7Fmrl6N3bgOeUGc',
    appId: '1:168592075849:web:618d3020c4c02ddc05e398',
    messagingSenderId: '168592075849',
    projectId: 'flutter-pro-firebase-3a2c5',
    authDomain: 'flutter-pro-firebase-3a2c5.firebaseapp.com',
    storageBucket: 'flutter-pro-firebase-3a2c5.firebasestorage.app',
    measurementId: 'G-12W225N61T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMbyvZa6RiCEYyiOLrgCw4UJtQEAXzhbI',
    appId: '1:168592075849:android:45768b9af78ca31e05e398',
    messagingSenderId: '168592075849',
    projectId: 'flutter-pro-firebase-3a2c5',
    storageBucket: 'flutter-pro-firebase-3a2c5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWwGjW6ifT-EdaHZyViH4tyvo__iDplaw',
    appId: '1:168592075849:ios:ba084535a99bf84a05e398',
    messagingSenderId: '168592075849',
    projectId: 'flutter-pro-firebase-3a2c5',
    storageBucket: 'flutter-pro-firebase-3a2c5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWwGjW6ifT-EdaHZyViH4tyvo__iDplaw',
    appId: '1:168592075849:ios:ba084535a99bf84a05e398',
    messagingSenderId: '168592075849',
    projectId: 'flutter-pro-firebase-3a2c5',
    storageBucket: 'flutter-pro-firebase-3a2c5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBuBetfcqPdxJeOV9J7Fmrl6N3bgOeUGc',
    appId: '1:168592075849:web:8ab8cc7c3c52064305e398',
    messagingSenderId: '168592075849',
    projectId: 'flutter-pro-firebase-3a2c5',
    authDomain: 'flutter-pro-firebase-3a2c5.firebaseapp.com',
    storageBucket: 'flutter-pro-firebase-3a2c5.firebasestorage.app',
    measurementId: 'G-N0YHH9H97V',
  );
}
