// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdhWts9mg50GYQHpYw0WQcLMSnj_VbOfk',
    appId: '1:745573474099:web:7234e9c892267811e7a846',
    messagingSenderId: '745573474099',
    projectId: 'myday1-f758c',
    authDomain: 'myday1-f758c.firebaseapp.com',
    storageBucket: 'myday1-f758c.firebasestorage.app',
    measurementId: 'G-NB56DHPE5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUW7WxHjm4H4c47OYE-ikxwbnFCgyRf7M',
    appId: '1:745573474099:android:7aaef72b05f8d6dde7a846',
    messagingSenderId: '745573474099',
    projectId: 'myday1-f758c',
    storageBucket: 'myday1-f758c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_r-WXuewDrxa12pkPRH95S6mikQmQT6U',
    appId: '1:745573474099:ios:aec89e9df9f1964be7a846',
    messagingSenderId: '745573474099',
    projectId: 'myday1-f758c',
    storageBucket: 'myday1-f758c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_r-WXuewDrxa12pkPRH95S6mikQmQT6U',
    appId: '1:745573474099:ios:aec89e9df9f1964be7a846',
    messagingSenderId: '745573474099',
    projectId: 'myday1-f758c',
    storageBucket: 'myday1-f758c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdhWts9mg50GYQHpYw0WQcLMSnj_VbOfk',
    appId: '1:745573474099:web:d04a9e42ea1b560de7a846',
    messagingSenderId: '745573474099',
    projectId: 'myday1-f758c',
    authDomain: 'myday1-f758c.firebaseapp.com',
    storageBucket: 'myday1-f758c.firebasestorage.app',
    measurementId: 'G-FX8CJN4FBF',
  );
}
